### PR TITLE
MSTR-76: Implement new port wizard

### PR DESCRIPTION
**Pull request by guillegr123**
5.0 -> #772

### CODE REVIEW

**Comment by guillegr123** [comment]
Thanks @azefiel. About the cancel button, I think I will remove it, because there are some instances (i.e. SmartPBX) where the close button is necessary to close the modal. And at the PBX Connector app, both Cancel and Close do the same action (closing the modal). So the Cancel button becomes unnecessary in these scenarios.

**Comment by guillegr123** [comment]
Closed PR by mistake. Reopening.

**Comment by guillegr123** [comment]
About the full-screen modal issues:

* On a second thought, I'll decided to re-add the cancel button, and just add some margin to prevent the overlapping with the modal close button, as the cancel button also allows to cancel (decline) previously saved port requests.
* Regarding to the bottom space, I've applied a quick fix by using viewport units, following the rules already defined for the navigation wizard control. However, I added a new ticket in Jira to refactor the control to use Flexbox, as it may require some work while keeping compatibility with current implementations in accounts, CCPro and AppExchange apps.

This PR is ready for a second review :smiley:

**Review by azefiel — DISMISSED** [review]
Looks good to me from what I've been able to test.

**Comment by azefiel** [comment]
Closing this and related PRs as it has become stale.

Feel free to reopen/recreate once this feature is ready for merge!

**Comment by guillegr123** [comment]
Reopening for review and merge.

**Comment by guillegr123** [comment]
The `MSTR-76` branch was rebased on top of current `master`. There were small conflicts mostly related to the Navigation Wizard submodule, which were fixed. This PR is ready for review again.

**Review by azefiel — APPROVED** [review]
Looks good, merge away!

**Pull request merged**
