### PR TITLE
MSTR-1: Tag selector common control

### PR DESCRIPTION
**Pull request by masmerino13**

### CODE REVIEW

**Comment by masmerino13** [comment]
Since this will be a common control that will be used in different modules, it will be nice to have your comments and suggestions @azefiel

**Comment by azefiel** [comment]
Just stumbled upon this http://sliptree.github.io/bootstrap-tokenfield/ and I wouldn't be against wrapping it in a `monster.ui` helper vs writing a common control as it implements all the features necessary for a tag selector.

**Comment by masmerino13** [comment]
Yeah, looks good to me, should this one works with monster UI Boostrap version?
cc: @azefiel

**Comment by azefiel** [comment]
I'd say don't import the library's CSS and instead, see with Josh what style this new component should take (be sure to ask the behavior for every state: disabled, validation, is there a specific behavior on hover, active etc).

**Comment by masmerino13** [comment]
Hey, I have noticed (thanks to Pilar) `Chosen` already have multiple selection that basically works like the same.

I think we can have a common control that receive array of tags and just personalize the default `chosen` styles?

cc: @azefiel

**Comment by azefiel** [comment]
`chosen` is just a fancy wrapper over `select` and only allows you to selected values from a predetermined list of `option` tags: you cannot add new options, which is kind the whole point of a tag selector.

**Comment by azefiel** [comment]
And as previously mentioned, this feature should be implemented as a UI helper (`monster.ui` method) rather than a full blown common control since it does not contain asynchronous operations.

**Comment by azefiel** [comment]
@masmerino13 

What was the decision on this, do we need a full-blown tag selector or using `chosen` with multi-selecting enabled enough for our purposes?

**Comment by azefiel** [comment]
@masmerino13 ping ^^

**Comment by masmerino13** [comment]
ups, sorry for the delay,

Doing a quick search, I found `chosen` can be customized as `text free` for multiple selections
http://jsfiddle.net/masmerino/etcb9n47/2/

What do you think about it?

cc: @azefiel

**Comment by masmerino13** [comment]
So, I think `chosen` do the job

**Comment by azefiel** [comment]
I thought you were supposed to talk to Mark and/or Josh to determine the requirements of this feature so we could decide which option was best.

**Comment by masmerino13** [comment]
Not yet,

I didn't talk to @mark2600 or Josh about this feature, we are just using chosen.

**Comment by azefiel** [comment]
@masmerino13 

Closing since we don't need this feature anymore.

**Pull request closed without merging**
