### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by powerpbx**
Add case of logging in with ApiKey generated tokens.

### CODE REVIEW

**Comment by JRMaitre** [comment]
Hello! Thanks for the PR, and it's a good point, we need a user id.

After checking the code, I think it would make more sense to use the same authenticateAuthToken method, but to change the success callback by something like:

```
/* Stuff */
else if(urlParams.hasOwnProperty('u') && urlParams.hasOwnProperty('t')) {
    self.authenticateAuthToken(urlParams.t, function(authData) {
        authData.data.owner_id = urlParams['u'];
        successFulAuth(authData);
    }, errorAuth);
}
// Username/password generated tokens do not require anything else to log in.
else if(urlParams.hasOwnProperty('t')) {
/* Stuff */
```

instead of referencing successfulAuth directly and using another GET request.

Does that make sense?

**Comment by powerpbx** [comment]
Glad you are open to adding this feature.  Your way makes more sense.

**Comment by JRMaitre** [comment]
Do you want to update the commit with the fix and I'll merge it down? :)

**Comment by powerpbx** [comment]
Not sure is your urlParams['u'] or urlParams.u is considered more correct.  Both seem to work so I went with the latter to make it consistent with `urlParams.t`

**Comment by JRMaitre** [comment]
Yep you're right! Thank you for the PR :)

**Pull request merged**
