### PR TITLE
Add preflow selection to account settings

### PR DESCRIPTION
**Pull request by mira-t**
This would allow users to select an existing callflow as an account-level preflow through Monster UI.

### CODE REVIEW

**Comment by JRMaitre** [comment]
Hi!

Did you know you could set this setting in the Callflows app? (Under account settings > misc > preflow settings)

If yes, is it just because you thought it'd be faster and easier to expose it in the MyAccount section?

The code looks good to me, but I'm not sure that this is a setting we want to expose there, so I'll have to ask our product team to see if it's OK. As a general rule of thumb we tend to only expose settings that most people use in the MyAccount section.

Thanks for the PR, and I'll get back to you soon!
JR

**Comment by mira-t** [comment]
Apologies, I did not know this was now available through the callflows app. Thank you very much for your help!

**Comment by JRMaitre** [comment]
No worries! Feel free to ask us questions via the community or IRC before developing it yourself, I hate to waste your work! :(

**Comment by mira-t** [comment]
I originally made this as a customization for a previous version of monster that didn't expose preflows, so I already had the changes and only needed to move it in and make sure it was compatible :) Next time I will have a better check if things have already been added!

**Pull request closed without merging**
