### PR TITLE
MCAR-18: Expose feature set flags to hide Storage Setting in Call Recording

### PR DESCRIPTION
**Pull request by Isaac2600Hz**

### CODE REVIEW

**Review by guillegr123 — APPROVED** [review]
Lgtm!

**Review by guillegr123 — APPROVED** [review]
Lgtm!

**Comment by ramandeepromana** [comment]
@guillegr123 @Isaac2600Hz shouldn't `storageSettings: { manage: }` be `false` instead of `true` for settings to hidden in the Call Recording application 🙂

**Comment by guillegr123** [comment]
You are absolutely right @ramandeepromana, the storage settings will be available when the value is `true`, and hidden when the value is `false`. Is it the intended behavior to show the storage setting for the feature set number 28, @Isaac2600Hz?

**Pull request merged**
