### PR TITLE
MSPB-172: Add support for 'Sugar' library to format dates for Office …

### PR DESCRIPTION
**Pull request by pcandia**
…Holidays

### CODE REVIEW

**Review by azefiel — COMMENTED** [review]
Since we're only interested in the `date` parsing functionality right now, have you looked at [customizing](https://sugarjs.com/download/#/Custom) the build to contain only that module?

**Comment by pcandia** [comment]
Yes, good point! Let me do that

**Review by azefiel — COMMENTED** [review]
Mind using `sugar-date` as module id, to match the npm module name?

It'd make sense for the file to match that name as well, since it only contains that specific module.

**Review by azefiel — COMMENTED** [review]
`sugar.min.js` is now included along `sugar-custom.min.js`, I believe we're only interested in the custom build, right?

**Comment by pcandia** [comment]
yes you are right! 👍

**Review by azefiel — APPROVED** [review]

**Pull request merged**
